import type { Metadata } from "next";
import { Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "../components/util/providers";
import Navbar from "./navbar";

const ubuntuMono = Ubuntu_Mono({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Kryp.Dev",
    description: "Generated by Kryp Arnold",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={ubuntuMono.className} suppressHydrationWarning>
                <Providers>
                    <Navbar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
