import type { Metadata } from "next";
import { Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";

const ubuntuMono = Ubuntu_Mono({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Kryp.Dev",
    description: "Generated by Kryp Arnold",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={ubuntuMono.className}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
