import type { Metadata } from "next";
import { Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeContext";

const ubuntuMono = Ubuntu_Mono({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Kryp.Dev",
    description: "Generated by Kryp Arnold",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ThemeProvider>
                <body className={ubuntuMono.className}>{children}</body>
            </ThemeProvider>
        </html>
    );
}
